name: mirrorchyan_release

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false
#   release:
#     types: [released]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    if: ${{ github.repository_owner == 'kqcoxn' }}
    strategy:
      fail-fast: false
      matrix:
        os: [win, macos, linux]
        arch: [aarch64, x86_64]
    steps:
      - uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: ${{ format('MaaDuDuL-{0}-{1}-*', matrix.os, matrix.arch) }}
          mirrorchyan_rid: MaaDuDuL
          tag: ${{ inputs.tag }}

          os: ${{ matrix.os }}
          arch: ${{ matrix.arch }}

          owner: kqcoxn
          repo: MaaDuDuL
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
