name: mirrorchyan_release_note

on:
  workflow_dispatch:
    inputs:
        tag:
            default: ''
            required: false
  release:
    types: [edited]

jobs:
  mirrorchyan:
    runs-on: macos-latest
    # if: ${{ github.repository_owner == 'kqcoxn' }}

    steps:
      - id: uploading
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: MaaDuDuL
          version_name: ${{ inputs.tag }}

          owner: kqcoxn
          repo: MaaDuDuL
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}
